// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProcessInfo {
    "pid": number;
    "parentPid": number;
    "name": string;
    "threadCount": number;

    /** Creates a new ProcessInfo instance. */
    constructor($$source: Partial<ProcessInfo> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("parentPid" in $$source)) {
            this["parentPid"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("threadCount" in $$source)) {
            this["threadCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfo($$parsedSource as Partial<ProcessInfo>);
    }
}

export class WindowBounds {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new WindowBounds instance. */
    constructor($$source: Partial<WindowBounds> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowBounds instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowBounds {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowBounds($$parsedSource as Partial<WindowBounds>);
    }
}
