// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function FindProcessesByName(processName: string): $CancellablePromise<$models.ProcessInfo[]> {
    return $Call.ByID(2775830862, processName).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMainWindowBounds(processName: string): $CancellablePromise<$models.WindowBounds | null> {
    return $Call.ByID(4018110840, processName).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetProcessPID(processName: string): $CancellablePromise<number> {
    return $Call.ByID(1251221914, processName);
}

export function InjectDLL(pid: number, dllPath: string): $CancellablePromise<void> {
    return $Call.ByID(2205823651, pid, dllPath);
}

export function Invoke(functionName: string, params: any[]): $CancellablePromise<any> {
    return $Call.ByID(2298258804, functionName, params);
}

export function IsDLLInjected(pid: number, dllPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(1963318352, pid, dllPath);
}

export function ListProcesses(): $CancellablePromise<$models.ProcessInfo[]> {
    return $Call.ByID(989120781).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SendCommand(command: number, ...params: any[]): $CancellablePromise<string> {
    return $Call.ByID(449610059, command, params);
}

export function SendCommandString(command: number, data: string): $CancellablePromise<string> {
    return $Call.ByID(759110190, command, data);
}

export function SetOverlayVisible(processName: string, visible: boolean): $CancellablePromise<void> {
    return $Call.ByID(3582890550, processName, visible);
}

export function SyncOverlayWindow(processName: string): $CancellablePromise<void> {
    return $Call.ByID(3777542549, processName);
}

export function TerminateProcess(pid: number): $CancellablePromise<void> {
    return $Call.ByID(3687413776, pid);
}

export function UnloadDLL(pid: number, dllPath: string): $CancellablePromise<void> {
    return $Call.ByID(252901713, pid, dllPath);
}

// Private type creation functions
const $$createType0 = $models.ProcessInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.WindowBounds.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
